import React, { useState } from 'react';
    import { ChevronDown, ChevronRight, Play, BookOpen, HelpCircle, Shield } from 'lucide-react';
    import Header from '../components/Header';
    import Footer from '../components/Footer';
    import TierBadge from '../components/TierBadge';

    const Tutorials = () => {
      const [activeSection, setActiveSection] = useState('getting-started');
      const [expandedFaq, setExpandedFaq] = useState<number | null>(null);

      const sections = [
        { id: 'getting-started', title: 'Getting Started', icon: Play },
        { id: 'tiers', title: 'How Tiers Work', icon: BookOpen },
        { id: 'deposits', title: 'Deposit Methods', icon: BookOpen },
        { id: 'faq', title: 'FAQ', icon: HelpCircle },
        { id: 'risk', title: 'Risk & Disclaimer', icon: Shield }
      ];

      const tiers = [
        { tier: 'TIER_1', range: '$1 - $200', multiplier: '1.80x', return: '80%' },
        { tier: 'TIER_2', range: '$200 - $500', multiplier: '2.00x', return: '100%' },
        { tier: 'TIER_3', range: '$500 - $1,000', multiplier: '2.20x', return: '120%' },
        { tier: 'TIER_4', range: '$1,000 - $5,000', multiplier: '2.50x', return: '150%' },
        { tier: 'TIER_5', range: '$5,000 - $10,000', multiplier: '3.00x', return: '200%' },
        { tier: 'TIER_6', range: '$10,000 - $30,000', multiplier: '4.00x', return: '300%' },
        { tier: 'TIER_7', range: '$30,000+', multiplier: '7.00x', return: '600%' }
      ];

      const faqs = [
        {
          question: "How long does a cycle last?",
          answer: "Each trading cycle lasts exactly 14 days. During this period, your deposited funds are used for automated trading simulations, and profits are calculated based on your tier multiplier."
        },
        {
          question: "Can I withdraw before a cycle ends?",
          answer: "No, withdrawals can only be requested after a cycle completes. This ensures maximum profit generation during the active trading period."
        },
        {
          question: "What if I don't make deposits regularly?",
          answer: "You can deposit at any time during a cycle. However, to maintain consistent profit generation, regular deposits help you advance to higher tiers with better multipliers."
        },
        {
          question: "How are referrals calculated?",
          answer: "You earn 6% of all profits generated by users you refer. This is calculated automatically when their cycles complete and profits are distributed."
        },
        {
          question: "What is the minimum deposit?",
          answer: "The minimum deposit is $2. This allows new users to start with a small amount and experience the platform before making larger investments."
        },
        {
          question: "Which blockchains are supported?",
          answer: "We support Ethereum (ETH), Binance Smart Chain (BSC), Solana (SOL), and Tron (TRX). Each has different confirmation times and network fees."
        },
        {
          question: "How are tiers determined?",
          answer: "Tiers are automatically calculated based on your account balance. As your balance grows, you're automatically upgraded to higher tiers with better multipliers."
        },
        {
          question: "What happens if my deposit fails?",
          answer: "If a deposit fails or is delayed beyond expected confirmation times, contact support with your transaction hash. Our team will investigate and assist with recovery if needed."
        },
        {
          question: "Are there any fees?",
          answer: "There's a 2% platform fee on withdrawals. Deposit fees depend on the blockchain network you choose. No fees are charged on profits or tier upgrades."
        },
        {
          question: "Is my money safe?",
          answer: "The platform uses secure wallet infrastructure and follows industry best practices. However, all trading involves risk, and you should only deposit amounts you can afford to lose."
        }
      ];

      const renderContent = () => {
        switch (activeSection) {
          case 'getting-started':
            return (
              <div className="space-y-8">
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 mb-4">Getting Started - 5 Steps</h2>
                  <p className="text-gray-600 mb-6">
                    Follow these simple steps to start your automated trading journey with RougeRunner GENESYS.
                  </p>
                </div>

                <div className="space-y-6">
                  {[
                    {
                      step: 1,
                      title: "Open the bot/webapp and press Start",
                      description: "Access RougeRunner GENESYS through Telegram or this web app. Complete the initial setup by pressing the Start button."
                    },
                    {
                      step: 2,
                      title: "Complete quick onboarding",
                      description: "Select your preferred language and optionally verify channel membership for bonus features."
                    },
                    {
                      step: 3,
                      title: "Make your first deposit",
                      description: "Go to Dashboard → Deposit. Select your preferred blockchain, enter amount, and send funds to the generated address."
                    },
                    {
                      step: 4,
                      title: "Wait for confirmation",
                      description: "Your deposit will be confirmed automatically. The webapp will notify you when funds are received and your balance is updated."
                    },
                    {
                      step: 5,
                      title: "Track your profits",
                      description: "When a 14-day cycle completes, profits are added automatically based on your tier. Check your Dashboard for updated balance and tier progression."
                    }
                  ].map((item) => (
                    <div key={item.step} className="flex items-start space-x-4 p-6 bg-gray-50 rounded-lg">
                      <div className="flex-shrink-0 w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold">
                        {item.step}
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-gray-900 mb-2">{item.title}</h3>
                        <p className="text-gray-600">{item.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            );

          case 'tiers':
            return (
              <div className="space-y-8">
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 mb-4">How the Tier System Works</h2>
                  <p className="text-gray-600 mb-6">
                    Your tier is automatically determined by your account balance. Higher tiers offer better multipliers and returns over the 14-day cycle period.
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {tiers.map((tier) => (
                    <div key={tier.tier} className="bg-white border border-gray-200 rounded-lg p-6 hover:shadow-md transition-shadow">
                      <div className="text-center mb-4">
                        <TierBadge tier={tier.tier} className="text-base px-4 py-2" />
                      </div>
                      <div className="space-y-3 text-sm">
                        <div className="flex justify-between">
                          <span className="text-gray-600">Deposit Range:</span>
                          <span className="font-medium">{tier.range}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Multiplier:</span>
                          <span className="font-medium">{tier.multiplier}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">14-Day Return:</span>
                          <span className="font-medium text-green-600">{tier.return}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
                  <h3 className="text-lg font-semibold text-blue-900 mb-3">How Tier Upgrades Work</h3>
                  <ul className="space-y-2 text-blue-800">
                    <li>• Tiers are calculated automatically based on your total account balance</li>
                    <li>• Upgrades happen immediately when you reach the next tier threshold</li>
                    <li>• Higher tiers mean better returns on your entire balance</li>
                    <li>• No manual action required - the system handles everything</li>
                  </ul>
                </div>
              </div>
            );

          case 'deposits':
            return (
              <div className="space-y-8">
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 mb-4">Deposit Methods</h2>
                  <p className="text-gray-600 mb-6">
                    We support multiple blockchain networks for deposits. Choose the one that works best for you.
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {[
                    {
                      name: 'Solana (SOL)',
                      confirmations: '30 seconds',
                      fees: 'Very Low',
                      description: 'Fast and cheap transactions. Recommended for frequent deposits.',
                      color: 'purple'
                    },
                    {
                      name: 'Binance Smart Chain (BSC)',
                      confirmations: '10 seconds',
                      fees: 'Low',
                      description: 'Quick confirmations with reasonable fees. Good for medium amounts.',
                      color: 'yellow'
                    },
                    {
                      name: 'Ethereum (ETH)',
                      confirmations: '2-5 minutes',
                      fees: 'Variable',
                      description: 'Most secure network. Fees vary based on network congestion.',
                      color: 'blue'
                    },
                    {
                      name: 'Tron (TRX)',
                      confirmations: '3 seconds',
                      fees: 'Very Low',
                      description: 'Ultra-fast confirmations with minimal fees.',
                      color: 'red'
                    }
                  ].map((chain) => (
                    <div key={chain.name} className="bg-white border border-gray-200 rounded-lg p-6">
                      <h3 className="text-lg font-semibold text-gray-900 mb-3">{chain.name}</h3>
                      <div className="space-y-2 text-sm mb-4">
                        <div className="flex justify-between">
                          <span className="text-gray-600">Confirmation Time:</span>
                          <span className="font-medium">{chain.confirmations}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-600">Network Fees:</span>
                          <span className="font-medium">{chain.fees}</span>
                        </div>
                      </div>
                      <p className="text-gray-600 text-sm">{chain.description}</p>
                    </div>
                  ))}
                </div>

                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
                  <h3 className="text-lg font-semibold text-yellow-900 mb-3">⚠️ Important Deposit Guidelines</h3>
                  <ul className="space-y-2 text-yellow-800">
                    <li>• Only send the specified cryptocurrency to each address</li>
                    <li>• Double-check the address before sending funds</li>
                    <li>• Send the exact amount shown in the deposit interface</li>
                    <li>• Wait for the required confirmations before expecting balance updates</li>
                    <li>• Contact support if your deposit doesn't appear after expected time</li>
                  </ul>
                </div>
              </div>
            );

          case 'faq':
            return (
              <div className="space-y-6">
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 mb-4">Frequently Asked Questions</h2>
                  <p className="text-gray-600 mb-6">
                    Find answers to common questions about RougeRunner GENESYS.
                  </p>
                </div>

                <div className="space-y-4">
                  {faqs.map((faq, index) => (
                    <div key={index} className="bg-white border border-gray-200 rounded-lg">
                      <button
                        onClick={() => setExpandedFaq(expandedFaq === index ? null : index)}
                        className="w-full px-6 py-4 text-left flex items-center justify-between hover:bg-gray-50 transition-colors"
                      >
                        <span className="font-medium text-gray-900">{faq.question}</span>
                        {expandedFaq === index ? (
                          <ChevronDown className="h-5 w-5 text-gray-500" />
                        ) : (
                          <ChevronRight className="h-5 w-5 text-gray-500" />
                        )}
                      </button>
                      {expandedFaq === index && (
                        <div className="px-6 pb-4">
                          <p className="text-gray-600">{faq.answer}</p>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            );

          case 'risk':
            return (
              <div className="space-y-8">
                <div>
                  <h2 className="text-2xl font-bold text-gray-900 mb-4">Risk Disclaimer</h2>
                  <p className="text-gray-600 mb-6">
                    Please read and understand these important risk factors before using RougeRunner GENESYS.
                  </p>
                </div>

                <div className="bg-red-50 border border-red-200 rounded-lg p-6">
                  <h3 className="text-lg font-semibold text-red-900 mb-4">⚠️ Important Risk Warnings</h3>
                  <div className="space-y-4 text-red-800">
                    <p>
                      <strong>Trading Risk:</strong> All trading activities carry inherent risk. Past performance 
                      does not guarantee future results. You may lose some or all of your deposited funds.
                    </p>
                    <p>
                      <strong>Technology Risk:</strong> Blockchain networks, smart contracts, and automated 
                      systems may experience technical issues, delays, or failures that could affect your funds.
                    </p>
                    <p>
                      <strong>Market Risk:</strong> Cryptocurrency markets are highly volatile and can experience 
                      significant price fluctuations that may impact returns.
                    </p>
                    <p>
                      <strong>Regulatory Risk:</strong> Changes in regulations or legal requirements may affect 
                      the operation of the platform or your ability to access funds.
                    </p>
                  </div>
                </div>

                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                  <h3 className="text-lg font-semibold text-gray-900 mb-4">Responsible Trading Guidelines</h3>
                  <ul className="space-y-2 text-gray-700">
                    <li>• Only deposit funds you can afford to lose completely</li>
                    <li>• Start with small amounts to understand the platform</li>
                    <li>• Diversify your investments across multiple platforms and strategies</li>
                    <li>• Regularly review your investment performance and risk tolerance</li>
                    <li>• Seek independent financial advice if needed</li>
                    <li>• Keep records of all transactions for tax purposes</li>
                  </ul>
                </div>

                <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
                  <h3 className="text-lg font-semibold text-blue-900 mb-4">Platform Disclaimers</h3>
                  <div className="space-y-3 text-blue-800 text-sm">
                    <p>
                      RougeRunner GENESYS provides automated trading simulation services. Results shown 
                      are based on algorithmic calculations and historical performance models.
                    </p>
                    <p>
                      The platform does not provide financial advice. All investment decisions are made 
                      solely by the user based on their own research and risk assessment.
                    </p>
                    <p>
                      By using this platform, you acknowledge that you understand these risks and agree 
                      to our Terms of Service and Privacy Policy.
                    </p>
                  </div>
                </div>
              </div>
            );

          default:
            return null;
        }
      };

      return (
        <div className="min-h-screen bg-gray-50">
          <Header />
          
          <main className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <div className="mb-8">
              <h1 className="text-3xl font-bold text-gray-900">Tutorials & Help</h1>
              <p className="mt-2 text-gray-600">
                Learn how to use RougeRunner GENESYS effectively and safely
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
              {/* Sidebar Navigation */}
              <div className="lg:col-span-1">
                <nav className="space-y-2">
                  {sections.map((section) => {
                    const Icon = section.icon;
                    return (
                      <button
                        key={section.id}
                        onClick={() => setActiveSection(section.id)}
                        className={`w-full flex items-center px-4 py-3 text-left rounded-lg transition-colors ${
                          activeSection === section.id
                            ? 'bg-blue-100 text-blue-700 border border-blue-200'
                            : 'text-gray-600 hover:bg-gray-100'
                        }`}
                      >
                        <Icon className="h-5 w-5 mr-3" />
                        {section.title}
                      </button>
                    );
                  })}
                </nav>
              </div>

              {/* Main Content */}
              <div className="lg:col-span-3">
                <div className="bg-white rounded-lg shadow-lg p-8">
                  {renderContent()}
                </div>
              </div>
            </div>
          </main>

          <Footer />
        </div>
      );
    };

    export default Tutorials;